### ISSUE TITLE
بکاپ با پسوند نامعتبر و همچنین فایل نامعتبر

### ISSUE THREAD

**Issue by LonUp** [erfjab/Backuper#10]
در بکاپ های چند پارت ای... وقتی روی 7z تست کردم ۳ تا فایل ارسال کرد . اولا که پسوندشون 7z نیست . و هیچ برنامه ای نمیخونه
دوما خودم دستی پسوندشون رو کردم 7z و باز هم فایل فشرده تشخیص داده نشد ... و وقتی با winrar یا 7z خواستم بازشون کنم ارور داد

![image](https://github.com/user-attachments/assets/4948fb9a-d4ac-4928-a4ca-ca7575a0b429)

![image](https://github.com/user-attachments/assets/f1b79829-eae0-4616-bddc-e26ae325cc94)

این مشکل در بکاپ های ۱ پارت ای پیش نیومده برام روی همین 7z

**Comment by erfjab** [comment]
درود و وقت بخیر ،عزیز شما اول باید باهم استخراج کنید. اینکارو کردید؟

**Comment by LonUp** [comment]
بله همه رو سلکت کردم که بعد اکسترکت رو زدم و بازم اروره
![image](https://github.com/user-attachments/assets/0bf6300f-187a-4e27-9b51-dc2f79a2565d)

**Comment by erfjab** [comment]
من داخل لینوکس تست کردم اوکیه.
لطفا صبر کنید نسخه‌ی جدید به‌زودی ریلیز میشه.
اونجا آموزش هاش کامل داده میشه.

**Comment by LonUp** [comment]
فایلای خروجی که ربات داده رو میتونم براتون ارسال کنم خودتون چک کنید

**Comment by erfjab** [comment]
اگه به فایل ها نیاز دارید بفرستید. 
ندارید صبر کنید میخوام آپدیت بدم.

**Comment by erfjab** [comment]
Fixed ✅
