### ISSUE TITLE
پشتیبانی از پروکسی بای استفاده در سرور های ایران

### ISSUE THREAD

**Issue by omid-j-d** [erfjab/Backuper#14]

**Comment by erfjab** [comment]
پینشهاد خوبیه 🤔

**Comment by mohamad3519** [comment]
لطفا پروکسی رو حتما اضافه کنید تا بتونیم از سرور های ایران هم بکاپ بفرستیم به تلگرام. ممنونم

**Comment by erfjab** [comment]
حالش نیس، ذاتا زود بسته میشه
پنلَهارو بیارید خارج
