### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by farshadl** [erfjab/Backuper#24]
عرفان‌جان، ممنون بابت تهیه Backuper.
اگه میتونستی یک فایل آموزشی یا یک ویدیو آموزشی برای استفاده از Backuper تهیه کنی خیلی خوب میشد.

**Comment by erfjab** [comment]
درود و وقت بخیر سلامت باشید. Dds عزیز به زودی ویدئوی کامل و دقیق منتشر خواهند کرد.
