### ISSUE TITLE
نمایش اسم پنل هنگام ارسال نشدن بکاپ

### ISSUE THREAD

**Issue by Alfred-13** [erfjab/Backuper#27]
هنگامی که ارور { Failed to send backup part: . Please check the server. } توسط ربات دریافت میشه هیچ اسم و نشانی از پنل نیست و لزوما اگر چند بکاپ روی یک ربات باشه نمیشه فهمیدم این ارور از کدوم پنل هست

**Comment by erfjab** [comment]
Added✅
