### ISSUE TITLE
امکان بکاپ گیری از چندین پنل روی یک ربات

### ISSUE THREAD

**Issue by LonUp** [erfjab/Backuper#9]
یکی از مشکلات رایج اینه ما باید برای هر پنل یک ربات درست کنیم که بکاپ بگیره
 . اگر امکان بکاپ گیری همزمان از چندین پنل روی یک ربات بود بسیار عالی تر میشد

**Comment by erfjab** [comment]
درود و وقت بخیر، شما می‌توانید با یه توکن بات هزاران بکاپر راه بندازید. مشکلی نمی‌سازه.
